trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    clean: true
    submodules: true
  - script: sudo apt-get install ninja-build

  - task: CMake@1
    inputs:
      cmakeArgs: '-G Ninja $(Build.SourcesDirectory)'

  - script: cd build && ninja

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    clean: true
    submodules: true
  - script: brew install ninja

  - task: CMake@1
    inputs:
      cmakeArgs: '-G Ninja $(Build.SourcesDirectory)'

  - script: cd build && ninja

- job: Windows_x64
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    clean: true
    submodules: true
  - task: CMake@1
    inputs:
      cmakeArgs: '-A x64 $(Build.SourcesDirectory)'

  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)/build/*.sln'
      maximumCpuCount: true
      platform: 'x64'

- job: Windows_x86
  pool:
    vmImage: 'windows-2019'

  steps:
  - checkout: self
    clean: true
    submodules: true
  - task: CMake@1
    inputs:
      cmakeArgs: '-A Win32 $(Build.SourcesDirectory)'

  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)/build/*.sln'
      maximumCpuCount: true
      platform: 'Win32'
