name: Deploy docs
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
        architecture: x64
        
    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get install doxygen

    - name: Build
      run: |
        python -m pip install --user virtualenv
        python -m venv _env
        python _env/Scripts/pip install sphinx
        python _env/Scripts/pip install breathe
        python _env/Scripts/pip install sphinx-bulma
        doxygen Doxygen
        python _env/Scripts/sphinx-build -Dbreathe_projects.format=docs/doxyxml -b html docs _build
        cd _build
        touch .nojekyll
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: 26435937+oAGoulart@users.noreply.github.com
        build_dir: _build/
        
